### PR TITLE
Fix #103: Disabling readonly anyOf/oneOf fields

### LINKED ISSUE #103: schema's `readonly` does not disable OneOf/AnyOf items
See reproduction in the Playground, modifying the AnyOf example to set readonly to true:

image

If the schema's `readonly` prop is true, other fields are correctly disabled, but fields in an `AnyOf` and/or `OneOf` are not.

### PR DESCRIPTION
**Pull request by glitchassassin**

### CODE REVIEW

**Comment by bhch** [comment]
Thanks for the PR.

Can you please include only the `src` files in the commit and exclude `dist` and other files outside of `src`.

`dist` builds are committed only for new releases.

Other than that, everything looks good.

**Comment by glitchassassin** [comment]
Done!

**Comment by glitchassassin** [comment]
@bhch just checking back in - anything else you need from me on this?

**Comment by bhch** [comment]
Sorry to have kept you waiting. I've merged the changes. I'll do a release in a few days. 

BTW, I'm currently working on a new library for generating JSON Schema forms. It will be completely customizable with the ability to write custom widgets, plugins etc, and a good development experience (with storybook etc.).

Repo: https://github.com/topspin-js/topspin. I haven't pushed anything yet but I will soon (I'm trying to clean up my local copy before pushing the code).

Again, thanks for the PR and wish you a happy new year.

**Comment by bhch** [comment]
Fixed in [v2.14.4](https://github.com/bhch/react-json-form/releases/tag/v2.14.4). 
Also released in [django-jsonform v2.23.2](https://github.com/bhch/django-jsonform/releases/tag/v2.23.2). 
Please update and test it out.
Thank you.

**Pull request merged**
